version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
          - not_null:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: unique identifier for each orders
          - name: products_id
            description: unique identifier for each products
          - name: revenue
            description: revenue made from each orders
          - name: quantity
            description: number of products ordered
      - name: product
        identifier: raw_gz_product
        description: products of Greeweez
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: ads performance metrics of Adwords
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name: "(date_date || '-' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: ads performance metrics of Bing
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name: "(date_date || '-' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: ads performance metrics of Criteo
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name: "(date_date || '-' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: ads performance metrics of Facebook
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name: "(date_date || '-' || campaign_key)"
